# Generated by Django 5.2.5 on 2025-08-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_Revenue', models.IntegerField()),
                ('total_Membership_Field', models.IntegerField()),
                ('top_Location', models.CharField()),
                ('quarters', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('date', models.CharField(max_length=40)),
                ('membership_Id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('activity', models.CharField()),
                ('revenue', models.IntegerField()),
                ('duration_Min', models.IntegerField()),
                ('location', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=256)),
                ('company_Revenue', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('employee_List', models.JSONField(default=list)),
                ('client_List', models.JSONField(default=list)),
                ('a_Performance_List', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('cashmoney', models.IntegerField()),
                ('hired_Date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('industry_Performance_List', models.JSONField(default=list)),
                ('company_List', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Industry_Quarters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(max_length=4)),
                ('revenue', models.IntegerField()),
                ('memberships_Sold', models.IntegerField()),
                ('avg_Duration_Mins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Q_Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(max_length=10)),
                ('memebrships_Sold', models.IntegerField()),
                ('avg_Duration_Min', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('profit_Margin', models.FloatField()),
            ],
        ),
    ]
