# Generated by Django 5.2.5 on 2025-08-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_performance',
            name='comapany_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='comapany_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='comapany_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='industry_quarters',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.industry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='q_performance',
            name='a_performance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.a_performance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.industry'),
        ),
    ]
