# Generated by Django 5.2.5 on 2025-08-18 06:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_a_performance_comapany_id_client_comapany_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_performance',
            name='quarters',
        ),
        migrations.RemoveField(
            model_name='company',
            name='a_Performance_List',
        ),
        migrations.RemoveField(
            model_name='company',
            name='client_List',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee_List',
        ),
        migrations.AlterField(
            model_name='industry',
            name='company_List',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=list), size=None),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_Performance_List',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=list), size=None),
        ),
    ]
