# Generated by Django 5.2.5 on 2025-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_a_performance_quarters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='company_List',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_Performance_List',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
