# Generated by Django 5.2.5 on 2025-08-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_industry_company_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='company_List',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='industry_Performance_List',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_Date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
