# Generated by Django 5.2.5 on 2025-08-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_industry_company_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='company_List',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='industry_Performance_List',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
