# Generated by Django 5.2.5 on 2025-08-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_industry_company_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry_quarters',
            name='id',
        ),
        migrations.AddField(
            model_name='industry_quarters',
            name='pk',
            field=models.CompositePrimaryKey('year', 'quarter', 'industry', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
