# Generated by Django 5.2.5 on 2025-08-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_industry_quarters_id_industry_quarters_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_Revenue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
