# Generated by Django 5.2.5 on 2025-08-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_employee_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='comapany_id',
            new_name='comapany',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='duration_Min',
            new_name='duration_min',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='membership_Id',
            new_name='membership_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='revenue',
            field=models.FloatField(),
        ),
    ]
