# Generated by Django 5.2.5 on 2025-08-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_comapany_id_client_comapany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='comapany',
        ),
    ]
