# Generated by Django 5.2.5 on 2025-08-20 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_client_comapany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a_performance',
            old_name='comapany_id',
            new_name='company',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.company'),
            preserve_default=False,
        ),
    ]
