# Generated by Django 5.2.5 on 2025-08-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_comapany_id_a_performance_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_Revenue',
            new_name='company_revenue',
        ),
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
    ]
