# Generated by Django 5.2.5 on 2025-08-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_company_revenue_company_company_revenue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a_performance',
            old_name='top_Location',
            new_name='top_location',
        ),
        migrations.RenameField(
            model_name='a_performance',
            old_name='total_Membership_Field',
            new_name='total_membership_sold',
        ),
        migrations.RenameField(
            model_name='a_performance',
            old_name='total_Revenue',
            new_name='total_revenue',
        ),
    ]
