# Generated by Django 5.2.5 on 2025-08-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_client_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='q_performance',
            old_name='avg_Duration_Min',
            new_name='avg_duration_min',
        ),
        migrations.RenameField(
            model_name='q_performance',
            old_name='memebrships_Sold',
            new_name='membership_sold',
        ),
        migrations.RenameField(
            model_name='q_performance',
            old_name='profit_Margin',
            new_name='profit_margin',
        ),
    ]
