# Generated by Django 5.2.5 on 2025-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_avg_duration_min_q_performance_avg_duration_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_performance',
            name='profit_margin',
            field=models.FloatField(null=True),
        ),
    ]
