# Generated by Django 5.2.5 on 2025-08-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_q_performance_profit_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_performance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='q_performance',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='A_Revenue_Distribution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gym', models.IntegerField()),
                ('pool', models.IntegerField()),
                ('tennis_court', models.IntegerField()),
                ('personal_training', models.IntegerField()),
                ('a_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.a_performance')),
            ],
        ),
    ]
