# Generated by Django 5.2.5 on 2025-08-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_a_performance_id_alter_q_performance_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry_quarters',
            name='pk',
        ),
        migrations.AddField(
            model_name='industry_quarters',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
