# Generated by Django 5.2.5 on 2025-08-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_document_remove_item_name_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
