# Generated by Django 5.2.5 on 2025-08-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_company_client_list_company_employee_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_performance',
            name='annual_rev_distribution_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='annual_performance_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
