# Generated by Django 5.2.5 on 2025-08-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_a_performance_annual_rev_distribution_list_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Industry_Quarters',
            new_name='Industry_Quarter',
        ),
    ]
