# Generated by Django 5.2.5 on 2025-08-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_rename_industry_quarters_industry_quarter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='company_List',
            new_name='company_list',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='industry_Performance_List',
            new_name='industry_performance_list',
        ),
    ]
