# Generated by Django 5.2.5 on 2025-08-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_company_list_industry_company_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_performance',
            name='quarter_performance_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
