# Generated by Django 5.2.5 on 2025-08-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_a_performance_quarter_performance_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
